apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sensu-client-infra
  namespace: sensu
  labels:
    app: sensu-client-infra
    component: client
spec:
  selector:
    matchLabels:
      app: sensu-client-infra
      component: client
  template:
    metadata:
      labels:
        app: sensu-client-infra
        component: client
    spec:
      imagePullSecrets:
      - name: docker-secret
      volumes:
        - name: sensu-config
          emptyDir: {}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule

      initContainers:
      - name: sensu-init
        args:
          - /bin/sh
          - -c
          - |
            client=$MY_NODE_NAME
            config=$(cat <<EOF
            {
              "redis": {
                "host": "sensu-redis-master",
                "port": 6379,
                "password": "",
                "db": 0,
                "auto_reconnect": true,
                "reconnect_on_error": true
              },
              "transport": {
                "name": "redis"
              },
              "api": {
                "host": "sensu-api",
                "port": 4567
              },
              "client": {
                "name": "$client",
                "deregister": true,
                "deregistration": {
                  "handler": "deregistration"
                },
                "subscriptions": [
                  "cpu",
                  "ram",
                  "disk"
                ]
              }
            }
            EOF
            )
            echo $config
            echo $config > /etc/sensu/conf.d/config.json
        image: busybox
        imagePullPolicy: Always
        volumeMounts:
          - name: sensu-config
            mountPath: /etc/sensu/conf.d/
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName


      containers:
      - name: sensu-client
        args:
          - client 
        env:
          - name: NO_CONFIGURE_DEFAULTS
            value: "true"
        image: sensu:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: sensu-config
            mountPath: /etc/sensu/conf.d/config.json
            subPath: config.json
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 30
