---
apiVersion: v1
data:
  config.json: |
    {
      "redis": {
        "host": "sensu-redis",
        "port": 6379,
        "password": "FL6vqYlbQu",
        "db": 0,
        "auto_reconnect": true,
        "reconnect_on_error": true
      },
      "transport": {
        "name": "redis"
      },
      "api": {
        "host": "sensu-api",
        "port": 4567
      },
      "client": {
        "name": "infra",
        "deregister": true,
        "deregistration": {
          "handler": "deregistration"
        },
        "subscriptions": [
          "cpu",
          "ram",
          "disk"
        ]
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: sensu-client-infra-config
  namespace: sensu
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sensu-client-infra
  namespace: sensu
  labels:
    app: sensu-client-infra
    component: client
spec:
  selector:
    matchLabels:
      app: sensu-client-infra
      component: client
  template:
    metadata:
      labels:
        app: sensu-client-infra
        component: client
    spec:
      volumes:
        - name: sensu-config
          configMap:
            name: sensu-client-infra-config
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: sensu-client
        args:
          - client 
        env:
          - name: NO_CONFIGURE_DEFAULTS
            value: "true"
        image: sensu:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: sensu-config
            mountPath: /etc/sensu/conf.d/config.json
            subPath: config.json
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 30
