apiVersion: v1
kind: Service
metadata:
  name: {{ template "sensu.api.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.api.serviceType }}
  ports:
  - port: {{ .Values.api.httpPort }}
    targetPort: {{ .Values.api.port }}
  selector:
    app: {{ template "sensu.fullname" . }}
