replicaCount: 1
imagePullSecrets:
  name: "gcr-credential"

server:
  image: "sensu"
  imageTag: "latest"
  pullPolicy: "Always"
  resources:
    resources:
      requests:
        cpu: 100m
        memory: 100Mi

api:
  image: "sensu"
  imageTag: "latest"
  pullPolicy: "Always"
  host: "localhost"
  resources:
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
  httpPort: 4567
  port: 4567
  serviceType: ClusterIP

uchiwa:
  image: "uchiwa/uchiwa"
  imageTag: "1.3.1-1"
  pullPolicy: "Always"
  user: admin
  pass: admin
  resources:
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
  serviceType: ClusterIP
  httpPort: 3000
  host: '0.0.0.0'
  port: 3000
  refresh: 5
  loglevel: info
  datacenterName: SENSU

# redis:
#   redis:
#     password: admin

slack:
  webhookUrl: "https://hooks.slack.com/services...."
  channel: "#slack-sensu"
  template: ""

handlers:
  default: "slack"


REDIS_PORT: 6379
REDIS_DB: 0
REDIS_AUTO_RECONNECT: true
REDIS_RECONNECT_ON_ERROR: true

